version = 1

dependencies = [
	"30BF2431", # Creepier Atmosphere
	"3417DBEF", # Hades Device
	"349DBD0F", # Healing Field
	"364799BA", # Smarter MAC
	"54711EA2", # Rebirth Bots
	"563B607D"  # Hide Skill Tiers
]

[branch.master]
name            = "Wooza's Hodgepodge"
tags            = ["Gameplay Tweak", "Must be run on Server"]
autodescription = true
description     = "README.txt"
preview         = "preview.jpg"
website         = "https://github.com/woozasmoddingteam/Wooza-s-Hodgepodge"

[branch.beta]
name            = "Wooza's Hodgepodge - Beta "
tags            = ["Gameplay Tweak", "Must be run on Server"]
autodescription = true
description     = "README.txt"
preview         = "preview.jpg"
website         = "https://github.com/woozasmoddingteam/Wooza-s-Hodgepodge"
